server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}

management:
  security:
    enabled: false