- name: load image from file
  command: "docker load --input /images/eureka_service.tar"
- name: install eureka server application
  docker_container:
    name: "eureka-server-application"
    image: "services_example/eureka_server:latest"
    state: started
    env:
      SERVER_PORT: "{{eureka_server_port}}"
      EUREKA_HOSTNAME: "{{eureka_hostname}}"
      EUREKA_URL: "{{eureka_server_url}}"
    etc_hosts: >
      {
        "{{current_server['name']}}": "{{current_server['host']}}",
        "{{another_server['name']}}": "{{another_server['host']}}"
      }
    ports:
      "{{eureka_server_port}}:{{eureka_server_port}}"
    restart: "{{restart}}"
    recreate: "{{recreate}}"
