---
- hosts: 127.0.0.1
  connection: local
  roles:
    - common
    - common-local

- hosts: api
  become: true
  vars:
    config_server: "{{vm_hosts[0]}}"
    current_server: "{{vm_hosts[0]}}"
    another_server: "{{vm_hosts[1]}}"
    recreate: true
    restart: true
  roles:
    - common
    - config-server
    - eureka-server
    - service1

- hosts: service
  become: true
  vars:
    config_server: "{{vm_hosts[0]}}"
    current_server: "{{vm_hosts[1]}}"
    another_server: "{{vm_hosts[0]}}"
    recreate: true
    restart: true
  roles:
    - common
    - eureka-server
    - service2
