require 'yaml'

configuration = YAML::load(File.read("#{File.dirname(__FILE__)}/common.yml"))

ANSIBLE_INVENTORY_DIR = '.vagrant/provisioners/ansible/inventory'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "vm#{i}"
      node.vm.network :private_network, ip: "192.168.5.#{i+1}"
      node.vm.network "forwarded_port", guest: "8080", host: "#{i}"

      node.vm.provider "virtualbox" do |v|
        v.memory = 2024
        v.cpus = 1
      end

      node.vm.provision "shell", privileged: false, inline: <<-EOF
        echo "register host from common config is #{configuration["registry_host"]}"
      EOF

      node.vm.provision "shell", inline: <<-SHELL
        sudo yum install -y yum-utils device-mapper-persistent-data lvm2
        sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo yum -y install docker-ce
        sudo yum -y install epel-release
        sudo yum -y install python-pip
        sudo pip install docker
        sudo systemctl start docker
      SHELL

      node.vm.provision "shell", inline: <<-SHELL
        sudo touch /etc/docker/daemon.json
        sudo echo "{
           \\\"insecure-registries\\\" : [
             \\\"#{configuration["registry_host"]}\\\"
           ]
         }" > /etc/docker/daemon.json
        sudo systemctl restart docker
      SHELL
    end
  end

  config.vm.provision "vai" do |ansible|
    ansible.inventory_dir=ANSIBLE_INVENTORY_DIR
    ansible.groups = {
      "api" => ["node-1"],
      "service" => ["node-2"]
    }
  end
end
