- name: start service2
  docker_container:
    name: "service2-application"
    image: "{{registry_host}}/services_example/service1:latest"
    state: started
    env:
      CONFIG_SERVER: "{{config_server_url}}"
      EUREKA_SERVER: "{{eureka_server_url}}"
      SERVER_PORT: "{{service_port}}"
    ports:
      "{{service_port}}:{{service_port}}"
    restart: "{{restart}}"
    recreate: "{{recreate}}"
